version: '3.8'

services:

  ashu-webapp:
    image: wordpress
    restart: always
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: database-1.ctoc084eswk5.us-east-1.rds.amazonaws.com
      WORDPRESS_DB_USER: admin
      WORDPRESS_DB_PASSWORD: Bmo1234567
      WORDPRESS_DB_NAME: helloashu
    