# create pipeline with some name 
name: ashu app containerization pipeline 
# Trigger -- when this pipeline should start
on:
  push:
    branches:
      - "master"

# jobs for performing operatiosn 
jobs:
  ashu-image-build:
    runs-on: ubuntu-latest
    # this server will be provision by github backen for this job
    steps:
      - name: run some basic commands on above server to do some verify 
        run: |
          uname -r 
          whoami
          cat /etc/os-release 
          docker version 
          docker-compose version 